al:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2026-01-01
  - chamber: lower
    district: 58
    vacant_until: 2026-01-01
  - chamber: upper
    district: 5
    vacant_until: 2026-01-01
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
ga:
  vacancies:
  - chamber: lower
    district: 61
    vacant_until: 2026-01-01
ia:
  vacancies:
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
ks:
  vacancies:
  - chamber: lower
    district: 35
    vacant_until: 2025-02-01
md:
  vacancies:
  - chamber: lower
    district: 38B
    vacant_until: 2025-02-01
mn:
  vacancies:
  - chamber: upper
    district: 45
    vacant_until: 2025-02-01
  - chamber: lower
    district: 50A
    vacant_until: 2025-02-01
  - chamber: lower
    district: 8A
    vacant_until: 2025-02-01
  - chamber: lower
    district: 58B
    vacant_until: 2025-02-01
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-02-01
  - chamber: upper
    district: 7
    vacant_until: 2025-02-01
  - chamber: upper
    district: 11
    vacant_until: 2025-02-01
  - chamber: upper
    district: 17
    vacant_until: 2025-02-01
  - chamber: upper
    district: 33
    vacant_until: 2025-02-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2025-02-01
nm:
  vacancies:
  - chamber: lower
    district: '6'
    vacant_until: 2025-02-01
ny:
  vacancies:
  - chamber: lower
    district: '148'
    vacant_until: 2025-02-01
oh:
  vacancies:
  - chamber: upper
    district: 29
    vacant_until: 2025-02-01
ok:
  vacancies:
  - chamber: upper
    district: '8'
    vacant_until: 2025-02-01
ri:
  vacancies:
  - chamber: upper
    district: 8
    vacant_until: 2025-02-01
  - chamber: upper
    district: 25
    vacant_until: 2025-02-01
sc:
  vacancies:
  - chamber: lower
    district: 113
    vacant_until: 2025-02-01
tx:
  vacancies:
  - chamber: lower
    district: 56
    vacant_until: 2025-02-01
us:
  vacancies:
  - chamber: lower
    district: AK-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: AL-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: AZ-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: AZ-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-12
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-13
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-16
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-27
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-29
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-30
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-45
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-47
    vacant_until: 2026-01-01
  - chamber: lower
    district: CO-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: CO-5
    vacant_until: 2026-01-01
  - chamber: lower
    district: CO-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: DE-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: FL-1
    vacant_until: 2026-01-01
  - chamber: lower
    district: FL-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: GA-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: IN-6
    vacant_until: 2026-01-01
  - chamber: lower
    district: IN-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: KS-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: MD-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: MD-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: MD-6
    vacant_until: 2026-01-01
  - chamber: lower
    district: MI-7
    vacant_until: 2026-01-01
  - chamber: lower
    district: MI-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: MN-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: MO-1
    vacant_until: 2026-01-01
  - chamber: lower
    district: MO-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: MP-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: MT-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: NC-10
    vacant_until: 2026-01-01
  - chamber: lower
    district: NC-13
    vacant_until: 2026-01-01
  - chamber: lower
    district: NC-6
    vacant_until: 2026-01-01
  - chamber: lower
    district: NC-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: NC-14
    vacant_until: 2026-01-01
  - chamber: lower
    district: ND-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: NJ-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: NJ-9
    vacant_until: 2026-01-01
  - chamber: lower
    district: NH-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: NY-16
    vacant_until: 2026-01-01
  - chamber: lower
    district: NY-19
    vacant_until: 2026-01-01
  - chamber: lower
    district: NY-22
    vacant_until: 2026-01-01
  - chamber: lower
    district: NY-4
    vacant_until: 2026-01-01
  - chamber: lower
    district: OH-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: OR-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: OR-5
    vacant_until: 2026-01-01
  - chamber: lower
    district: PA-7
    vacant_until: 2026-01-01
  - chamber: lower
    district: PA-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: PR-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: SC-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-12
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-18
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-26
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-32
    vacant_until: 2026-01-01
  - chamber: lower
    district: UT-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-10
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-5
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-7
    vacant_until: 2026-01-01
  - chamber: lower
    district: WA-5
    vacant_until: 2026-01-01
  - chamber: lower
    district: WA-6
    vacant_until: 2026-01-01
  - chamber: lower
    district: WV-2
    vacant_until: 2026-01-01
  - chamber: upper
    district: Maryland
    vacant_until: 2026-01-01
  - chamber: upper
    district: Montana
    vacant_until: 2026-01-01
  - chamber: upper
    district: Ohio
    vacant_until: 2026-01-01
  - chamber: upper
    district: Pennsylvania
    vacant_until: 2026-01-01
  - chamber: upper
    district: West Virginia
    vacant_until: 2026-01-01
ut:
  vacancies:
  - chamber: upper
    district: '21'
    vacant_until: 2026-01-01
wa:
  vacancies:
  - chamber: upper
    district: 24
    vacant_until: 2025-02-01
wi:
  vacancies:
  - chamber: upper
    district: 4
    vacant_until: 2025-02-01
  - chamber: lower
    district: 9
    vacant_until: 2025-02-01
