al:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2026-01-01
  - chamber: upper
    district: '36'
    vacant_until: 2026-01-01
co:
  vacancies:
  - chamber: lower
    district: '41'
    vacant_until: 2026-01-01
ct:
  vacancies:
  - chamber: lower
    district: '40'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '21'
    vacant_until: 2026-01-01
de:
  vacancies:
  - chamber: upper
    district: '1'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
fl:
  vacancies:
  - chamber: lower
    district: '3'
    vacant_until: 2026-01-01
ia:
  vacancies:
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
la:
  vacancies:
  - chamber: upper
    district: '14'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '23'
    vacant_until: 2026-01-01
md:
  vacancies:
  - chamber: lower
    district: 30A
    vacant_until: 2026-01-01
  - chamber: upper
    district: '41'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '8'
    vacant_until: 2026-01-01
me:
  vacancies:
  - chamber: lower
    district: '24'
    vacant_until: 2026-01-01
mi:
  vacancies:
  - chamber: upper
    district: 35
    vacant_until: 2025-02-01
mn:
  vacancies:
  - chamber: lower
    district: 40B
    vacant_until: 2026-01-01
  - chamber: upper
    district: 60
    vacant_until: 2026-01-01
ms:
  vacancies:
  - chamber: lower
    district: '23'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '82'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '18'
    vacant_until: 2026-01-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2025-02-01
nj:
  vacancies:
  - chamber: lower
    district: '7'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
nm:
  vacancies:
  - chamber: lower
    district: '6'
    vacant_until: 2025-02-01
oh:
  vacancies:
  - chamber: upper
    district: 29
    vacant_until: 2025-02-01
ok:
  vacancies:
  - chamber: lower
    district: '74'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '8'
    vacant_until: 2025-02-01
sc:
  vacancies:
  - chamber: lower
    district: 113
    vacant_until: 2025-02-01
us:
  vacancies:
  - chamber: lower
    district: FL-1
    vacant_until: 2026-01-01
  - chamber: lower
    district: FL-6
    vacant_until: 2026-01-01
wv:
  vacancies:
  - chamber: lower
    district: '89'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '91'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '17'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '8'
    vacant_until: 2026-01-01
