ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2026-01-01
  - chamber: lower
    district: 58
    vacant_until: 2026-01-01
  - chamber: upper
    district: 5
    vacant_until: 2026-01-01
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
ga:
  vacancies:
  - chamber: lower
    district: 61
    vacant_until: 2025-01-01
ia:
  vacancies:
  - chamber: upper
    district: 30
    vacant_until: 2025-01-01
ks:
  vacancies:
  - chamber: lower
    district: 35
    vacant_until: 2025-01-01
ky:
  vacancies:
  - chamber: lower
    district: '2'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '11'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '24'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '29'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '41'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '42'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '45'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '57'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '62'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '66'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '67'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '76'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '88'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '94'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '98'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '3'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '7'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '11'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '17'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '29'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
md:
  vacancies:
  - chamber: lower
    district: 38B
    vacant_until: 2025-01-01
mn:
  vacancies:
  - chamber: upper
    district: 45
    vacant_until: 2025-01-01
  - chamber: lower
    district: 50A
    vacant_until: 2025-01-01
  - chamber: lower
    district: 8A
    vacant_until: 2025-01-01
  - chamber: lower
    district: 58B
    vacant_until: 2025-01-01
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-01-01
  - chamber: upper
    district: 7
    vacant_until: 2025-01-01
  - chamber: upper
    district: 11
    vacant_until: 2025-01-01
  - chamber: upper
    district: 17
    vacant_until: 2025-01-01
  - chamber: upper
    district: 33
    vacant_until: 2025-01-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2025-01-01
ny:
  vacancies:
  - chamber: upper
    district: 63
    vacant_until: 2025-01-01
  - chamber: lower
    district: 85
    vacant_until: 2025-01-01
  - chamber: lower
    district: 96
    vacant_until: 2025-01-01
ok:
  vacancies:
  - chamber: upper
    district: '8'
    vacant_until: 2025-01-01
ri:
  vacancies:
  - chamber: upper
    district: 8
    vacant_until: 2025-01-01
  - chamber: upper
    district: 25
    vacant_until: 2025-01-01
sc:
  vacancies:
  - chamber: lower
    district: 113
    vacant_until: 2025-01-01
tx:
  vacancies:
  - chamber: lower
    district: 56
    vacant_until: 2025-01-01
us:
  vacancies:
  - chamber: lower
    district: NJ-9
    vacant_until: 2025-01-02
  - chamber: lower
    district: NJ-3
    vacant_until: 2025-01-02
  - chamber: lower
    district: CA-30
    vacant_until: 2025-01-02
wa:
  vacancies:
  - chamber: upper
    district: 24
    vacant_until: 2025-01-01
wi:
  vacancies:
  - chamber: upper
    district: 4
    vacant_until: 2025-01-01
  - chamber: lower
    district: 9
    vacant_until: 2025-01-01
