ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2026-01-01
  - chamber: lower
    district: 58
    vacant_until: 2026-01-01
  - chamber: upper
    district: 5
    vacant_until: 2026-01-01
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
ga:
  vacancies:
  - chamber: lower
    district: 61
    vacant_until: 2026-01-01
ia:
  vacancies:
  - chamber: upper
    district: 30
    vacant_until: 2025-02-01
ks:
  vacancies:
  - chamber: lower
    district: 35
    vacant_until: 2025-02-01
md:
  vacancies:
  - chamber: lower
    district: 38B
    vacant_until: 2025-02-01
#mi:
#  vacancies:
#  - chamber: lower
#    district: '107'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '109'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '27'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '33'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '34'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '35'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '40'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '44'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '50'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '58'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '64'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '81'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '9'
#    vacant_until: 2026-01-01
#  - chamber: lower
#    district: '93'
#    vacant_until: 2026-01-01
mn:
  vacancies:
  - chamber: upper
    district: 45
    vacant_until: 2025-02-01
  - chamber: lower
    district: 50A
    vacant_until: 2025-02-01
  - chamber: lower
    district: 8A
    vacant_until: 2025-02-01
  - chamber: lower
    district: 58B
    vacant_until: 2025-02-01
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-02-01
  - chamber: upper
    district: 7
    vacant_until: 2025-02-01
  - chamber: upper
    district: 11
    vacant_until: 2025-02-01
  - chamber: upper
    district: 17
    vacant_until: 2025-02-01
  - chamber: upper
    district: 33
    vacant_until: 2025-02-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2025-02-01
ny:
  vacancies:
  - chamber: upper
    district: 63
    vacant_until: 2025-02-01
  - chamber: lower
    district: 85
    vacant_until: 2025-02-01
  - chamber: lower
    district: 96
    vacant_until: 2025-02-01
ok:
  vacancies:
  - chamber: upper
    district: '8'
    vacant_until: 2025-02-01
ri:
  vacancies:
  - chamber: upper
    district: 8
    vacant_until: 2025-02-01
  - chamber: upper
    district: 25
    vacant_until: 2025-02-01
sc:
  vacancies:
  - chamber: lower
    district: 113
    vacant_until: 2025-02-01
tx:
  vacancies:
  - chamber: lower
    district: 56
    vacant_until: 2025-02-01
us:
  vacancies:
  - chamber: lower
    district: NJ-9
    vacant_until: 2025-01-02
  - chamber: lower
    district: NJ-3
    vacant_until: 2025-01-02
  - chamber: lower
    district: CA-30
    vacant_until: 2025-01-02
wa:
  vacancies:
  - chamber: upper
    district: 24
    vacant_until: 2025-02-01
wi:
  vacancies:
  - chamber: upper
    district: 4
    vacant_until: 2025-02-01
  - chamber: lower
    district: 9
    vacant_until: 2025-02-01
