al:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2026-01-01
ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2026-01-01
  - chamber: upper
    district: 35
    vacant_until: 2026-01-01
  - chamber: upper
    district: '36'
    vacant_until: 2026-01-01
  - chamber: upper
    district: 5
    vacant_until: 2026-01-01
co:
  vacancies:
  - chamber: upper
    district: '30'
    vacant_until: 2026-01-01
ct:
  vacancies:
  - chamber: lower
    district: '102'
    vacant_until: 2026-01-01
de:
  vacancies:
  - chamber: upper
    district: '1'
    vacant_until: 2026-01-01
fl:
  vacancies:
  - chamber: lower
    district: '3'
    vacant_until: 2026-01-01
ga:
  vacancies:
  - chamber: lower
    district: '97'
    vacant_until: 2026-01-01
ia:
  vacancies:
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
il:
  vacancies:
  - chamber: upper
    district: '20'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '53'
    vacant_until: 2026-01-01
md:
  vacancies:
  - chamber: lower
    district: 38B
    vacant_until: 2025-02-01
  - chamber: upper
    district: 30
    vacant_until: 2025-02-01
mi:
  vacancies:
  - chamber: upper
    district: 35
    vacant_until: 2025-02-01
mn:
  vacancies:
  - chamber: lower
    district: 40B
    vacant_until: 2026-01-01
  - chamber: upper
    district: 60
    vacant_until: 2026-01-01
nh:
  vacancies:
  - chamber: lower
    district: Strafford 12
    vacant_until: 2025-02-01
nj:
  vacancies:
  - chamber: lower
    district: '6'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '7'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '35'
    vacant_until: 2026-01-01
nm:
  vacancies:
  - chamber: lower
    district: '6'
    vacant_until: 2025-02-01
ny:
  vacancies:
  - chamber: lower
    district: '148'
    vacant_until: 2025-02-01
oh:
  vacancies:
  - chamber: upper
    district: 29
    vacant_until: 2025-02-01
ok:
  vacancies:
  - chamber: upper
    district: '8'
    vacant_until: 2025-02-01
or:
  vacancies:
  - chamber: lower
    district: '39'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '46'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '34'
    vacant_until: 2026-01-01
sc:
  vacancies:
  - chamber: lower
    district: 113
    vacant_until: 2025-02-01
tx:
  vacancies:
  - chamber: lower
    district: '115'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '97'
    vacant_until: 2026-01-01
us:
  vacancies:
  - chamber: lower
    district: CA-30
    vacant_until: 2026-01-01
  - chamber: lower
    district: CA-47
    vacant_until: 2026-01-01
  - chamber: lower
    district: CO-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: FL-1
    vacant_until: 2026-01-01
  - chamber: upper
    district: West Virginia
    vacant_until: 2026-01-01
  - chamber: lower
    district: DE-AL
    vacant_until: 2026-01-01
  - chamber: lower
    district: FL-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: IN-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: MI-8
    vacant_until: 2026-01-01
  - chamber: lower
    district: MN-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: MO-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: NJ-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-18
    vacant_until: 2026-01-01
  - chamber: lower
    district: VA-10
    vacant_until: 2026-01-01
  - chamber: lower
    district: WA-6
    vacant_until: 2026-01-01
  - chamber: lower
    district: WV-2
    vacant_until: 2026-01-01
  - chamber: lower
    district: NJ-9
    vacant_until: 2026-01-01
  - chamber: lower
    district: NY-16
    vacant_until: 2026-01-01
  - chamber: lower
    district: OR-3
    vacant_until: 2026-01-01
  - chamber: lower
    district: TX-12
    vacant_until: 2026-01-01
va:
  vacancies:
  - chamber: upper
    district: '10'
    vacant_until: 2026-01-01
  - chamber: upper
    district: '32'
    vacant_until: 2026-01-01
vt:
  vacancies:
  - chamber: lower
    district: Bennington-5
    vacant_until: 2026-01-01
  - chamber: upper
    district: Bennington
    vacant_until: 2026-01-01
  - chamber: upper
    district: Washington
    vacant_until: 2026-01-01
wa:
  vacancies:
  - chamber: lower
    district: '12'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '14'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '17'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '22'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '3'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '4'
    vacant_until: 2026-01-01
  - chamber: lower
    district: '5'
    vacant_until: 2026-01-01
wi:
  vacancies:
  - chamber: lower
    district: '24'
    vacant_until: 2026-02-01
wv:
  vacancies:
  - chamber: upper
    district: '15'
    vacant_until: 2026-01-01
